In [1]:
# Write a dynamic programming based program to find minimum number insertions (addition) needed to make a palindrome 

# Examples:
# ab: Number of insertions required is 1 i.e. bab    aa: Number of insertions required is 0 i.e. aa
# abcd: Number of insertions required is 3 i.e. dcb + abcd

# Algorithm:
# The table should be filled in diagonal fashion. For the string abcde, 0….4, 
# the following should be order in which the table is filled:

# Gap = 1: (0, 1) (1, 2) (2, 3) (3, 4)  --> l, h values
# Gap = 2: (0, 2) (1, 3) (2, 4)
# Gap = 3: (0, 3) (1, 4)
# Gap = 4: (0, 4)

import numpy as np

def min_insertions_for_palindrome(str1): # look for similar letters at the edges and calculate the steps needed to make it similar
    n = len(str1)
    # Create a table of size n*n to store minimum number of insertions  
    # needed to convert str1[l..h] to a palindrome. Fill the table diagonally
    table = np.zeros([n,n], dtype = int)
    for gap in range(1, n): 
        l = 0
        for h in range(gap, n): 
            # if the beginning and ending letters are the same, move one index towards inner part of the string
            # Ex iovoi then the next step is to check ovo
            if str1[l] == str1[h]: 
                table[l][h] = table[l + 1][h - 1] 
            # if the letters at both edges are not the same, look for either moving from one side or the other
            # find the minimum and add one more step
            else: 
                table[l][h] = (min(table[l][h - 1], table[l + 1][h]) + 1) 
            l += 1
    
    print(table)
    # Return minimum number of insertions for str1[0..n-1] 
    return table[0][n - 1]; 
  
# Driver Code 
test_str = "vyoili"
print(min_insertions_for_palindrome(test_str)) 
  


[[0 1 2 3 4 3]
 [0 0 1 2 3 2]
 [0 0 0 1 2 1]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]]
3


In [2]:
# Minimum insertions to form a palindrome can be found easily by using Longest Common Subsequence Algorithm
# Find the LCS of the string and its reverse. Items that are not in LCS are the ones missing to form a palindrome

test_str = "ilivyo"
rev = "".join(list(reversed(test_str)))
print(rev)

def lcsubs(string):
    reverse_string = "".join(list(reversed(string)))
    n = len(string)
    lcsubs_list = []
    dp = np.zeros([n+1, n+1], dtype = int)
    for i in range(1, n+1):
        for j in range(1 , n+1):
            if string[i-1] == reverse_string[j-1]:
                dp[i][j] = dp[i-1][j-1] + 1
            else:
                dp[i][j] = max(dp[i-1][j], dp[i][j-1])
    
    i = n
    j = n
    while i > 0 and j > 0:
        if string[i-1] == reverse_string[j-1]:
            lcsubs_list.insert(0, string[i-1])
            i -= 1
            j -= 1
        elif dp[i-1][j] > dp[i][j-1]:
            i -= 1
        else:
            j -= 1
    
    a_dict = {} # append the items needed to make the array palindrome
    for i in range(len(string)):
        if string[i] not in lcsubs_list:
            a_dict[string[i]] = 'Needed'
    print("these items are needed to add the string to make a palindrome")
    return a_dict.keys()
    
lcsubs(test_str)  
    
    

oyvili
these items are needed to add the string to make a palindrome


dict_keys(['v', 'y', 'o'])

In [3]:
# Python program to maximize the profit by doing at most k transactions given stock prices for n days 

def max_profit(prices, k): 
    n = len(prices)
    if k > n: return
    # Bottom-up DP approach 
    profit = np.zeros([n, k+1]) 
    # Profit is zero for the first 
    # day and for zero transactions 
    for j in range(1, k+1): # for each transaction 
        for i in range(1, n): # for each day's stock value
            max_so_far = 0
            for l in range(i): # for all past transactions
                max_so_far = max(max_so_far, prices[i] - prices[l] + profit[l][j-1])               
            profit[i][j] = max(profit[i - 1][j], max_so_far) 
    
    print(profit) # to view the table
    return profit[n - 1][k] 
  
# Driver code 
k = 3
prices = [10, 22, 5, 75, 65, 80] 
n = len(prices) 
  
print("Maximum profit is:", max_profit(prices, k)) 
  
# if k = 2, trader earns 87 as sum of 12 and 75 Buy at price 10, sell at 22, buy at 5 and sell at 80,

[[ 0.  0.  0.  0.]
 [ 0. 12. 12. 12.]
 [ 0. 12. 12. 12.]
 [ 0. 70. 82. 82.]
 [ 0. 70. 82. 82.]
 [ 0. 75. 87. 97.]]
Maximum profit is: 97.0


In [4]:
# Alternative solution to maximize the profit by doing at most k transactions given stock prices for n days 

import numpy as np
def maximize_profit_with_k_trsc(price_list, k):
    n = len(price_list)
    if n <= 1 or k > len(price_list): return 0
    memo_table = np.zeros([k+1, n+1] , dtype = int)  # number of transactions in rows
    for i in range(1, k+1): # for each buy and sell transaction, i
        max_profit = -np.inf
        for j in range(1, n+1): # for each day, j, starting from the first day
            prev_day_prev_transact = memo_table[i-1][j-1] # max profit until prev day with prev transact capacity
            price_today = price_list[j-1]
            prev_day_price = price_list[j-2]
            max_transaction_until_today = memo_table[i][j-1] # max profit reached until prev day with curr transact.
            max_profit = max(max_profit, prev_day_prev_transact - prev_day_price)
            memo_table[i][j] = max(max_transaction_until_today, max_profit + price_today)
    
    print(memo_table)
    return memo_table[k][n]      
            
prices = [10, 22, 5, 75, 65, 80] 
maximize_profit_with_k_trsc(prices, 3)

[[ 0  0  0  0  0  0  0]
 [ 0  0 12 12 70 70 75]
 [ 0  0 12 12 82 82 87]
 [ 0  0 12 12 82 82 97]]


97

In [5]:
# Return the list of items of the shortest supersequence of X and Y strings

import numpy as np
def shortest_supersequence(X, Y): 
    m = len(X)
    n = len(Y)
    memo_list = np.zeros([m+1, n+1], dtype = int)

    for i in range(1, m + 1): 
        for j in range(1, n+1): 
            memo_list[0][j] = j # if there is no item in the X string, the result is length of Y
            memo_list[i][0] = i # if there is no item in the Y string, the result is length of X
              
            if (X[i - 1] == Y[j - 1]):  
                memo_list[i][j] = 1 + memo_list[i - 1][j - 1] 
                   
            else: 
                memo_list[i][j] = 1 + min(memo_list[i - 1][j], memo_list[i][j - 1]) 
    
    print(memo_list) # to view
    print(memo_list[m][n]) # answer to the length of the supersequence
  
    i = m 
    j = n 
    result = []
    while i > 0 and j > 0: 
        if X[i - 1] == Y[j - 1]: 
            result.insert(0, X[i-1]) 
            i -= 1
            j -= 1

        elif memo_list[i - 1][j] > memo_list[i][j - 1]: 
            result.insert(0, Y[j-1]) 
            j -= 1

        else: 
            result.insert(0, X[i-1]) 
            i -= 1

    # if j == 0
    while i > 0: 
        result.insert(0, X[i-1])  
        i -= 1

    
    #if i == 0
    while j > 0: 
        result.insert(0, Y[j-1]) 
        j -= 1

  
    return result
    
test_x = "VKLAB"
test_y = "ZKADB"
shortest_supersequence(test_x, test_y)

[[0 1 2 3 4 5]
 [1 2 3 4 5 6]
 [2 3 3 4 5 6]
 [3 4 4 5 6 7]
 [4 5 5 5 6 7]
 [5 6 6 6 7 7]]
7


['Z', 'V', 'K', 'L', 'A', 'D', 'B']

In [6]:
# Reminder of the min coin change problem to help the min cost table and max chain problems below

change_list = [1,3,5,10]
target = 21
def min_coin_change(coin_list,change):
    # create an array for the worst number of coins for change 
    dp = np.arange(change + 1, dtype = int)
    # optimize the array for the min number of coins 
    for i in range(1, len(dp)):
        for c in [coin for coin in coin_list if coin <= i]:
            dp[i] = min(dp[i], dp[i-c] + 1)
    # print(dp)
    return dp[change]
print(min_coin_change(change_list, target))


3


In [7]:
# min cost table for addition or multiplication with unusual operational costs:
# if from zero to the destination(N), the cost of addition(P) of 1 unit is 5, and multiplication cost by two(Q) is 1;
# find the min cost to reach to destination from 0
# Input: N = 9, P = 5, Q = 1 Min cost is: 13 :  0 --> 1 --> 2 --> 4 --> 8 --> 9  is:  5 + 1 + 1 + 1 + 5 = 13. 

import numpy as np
def min_cost_to_reach_N(N, P, Q):
    # prepare the memory array with the worst case scenerio (with addition of P for each unit) to reach any number
    memo = np.zeros(N + 1, dtype = int)
    for i in range(1, len(memo)):
        memo[i] = i*P
    # loop over the memo array to optimize the values in the array
    for i in range(1, len(memo)):
        # the index of memo can be odd or even
        if i % 2 == 0:
            memo[i] = min(memo[i-1] + 5, memo[i//2] + 1 )
        else:
            memo[i] = min(memo[i-1] + 5, memo[i//2] + 1 + 5) 
    print(np.arange(len(memo)), memo)
    return memo[N]
    
min_cost_to_reach_N(9, 5,1)  #[ 0  5  6 11  7 12 12 17  8 13]

[0 1 2 3 4 5 6 7 8 9] [ 0  5  6 11  7 12 12 17  8 13]


13

In [8]:
# Order shuffled pairs such as: (a, b),(c, d),(e, f)... if c > b and e > f.. Find the longest chain from a given set
# Input: {{5, 24}, {41, 50}, {25, 68}, {27, 39}, {30, 90}}, then the longest chain is: {{5, 24}, {27, 39}, {41, 50}}
        
def max_chain_length_of_tuples(arr): 
    arr = sorted(arr, key = lambda x: x[0]) # sort the array of tuples according to the first value
    n = len(arr)
    max_length = 0
    # Initialize MCL(max chain length) values for all indices 
    memo = [1 for i in range(n)] 
    # Compute optimized chain length values in bottom up manner 
    for i in range(1, n): 
        for j in range(0, i): 
            if (arr[i][0] > arr[j][1] and memo[i] <= memo[j]): 
                memo[i] = memo[j] + 1
    print(memo)
    return max(memo)
  
# Driver program to test above function 
arr = [(5, 24), (41, 50), (25, 68), (27, 39), (70,90)] 
  
max_chain_length_of_tuples(arr)

[1, 2, 2, 3, 4]


4

In [9]:
# Longest Increasing Subsequence Algorithm can be applied to find a solution to this problem.
# Because the items are shuffled, it wouldn't be useful to print the order

# def LIS(numbers):  # with two for loops, simple Longest Increasing Subsequence
#     n = len(numbers)
#     ranking = [1 for i in range(n)] # ranking is set to 1, if there is no sequence, it will be just one number
#     for i in range(n):  # all the numbers
#         for j in range(i+1, len(numbers)):
#             # check if the remaining items have lower rank but higher value and re-adjust the ranking
#             if numbers[i] < numbers[j] and ranking[i] >= ranking[j]:
#                 ranking[j] = ranking[i] + 1
                
#     return max(ranking) , ranking
# LIS([4, 0, 1, 8, 2, 10, 2]

def max_chain_length_of_tuples2(arr): 
    arr = sorted(arr, key = lambda x: x[0]) # sort the array of tuples according to the first value
    n = len(arr)
    max_length = 0
    # Initialize MCL(max chain length) values for all indices 
    memo = [1 for i in range(n)] 
    # Compute optimized chain length values in bottom up manner 
    for i in range(n): 
        for j in range(i, n): 
            if (arr[j][0] > arr[i][1] and memo[i] >= memo[j]): 
                memo[j] = memo[i] + 1
    print(memo)
    return max(memo)
  
# Driver program to test above function 
arr = [(5, 24), (41, 50), (25, 68), (27, 39), (70,90)] 
  
max_chain_length_of_tuples2(arr)

[1, 2, 2, 3, 4]


4

In [10]:
# Reminder of the Longest Increasing Subsequence problem before the Longest Common Increasing Subsequence problem
# ATTN: There might always be several longest increasing subsequences with same length 
# ex: [4, 5, 0, 1, 8, 2, 10]  answer: 4,5,8,10 and 0,1,2,10

test_array = [4, 0, 1, 8, 2, 10]
def longest_increasing_subsequence(a):
    # create a ranking array and a parent array
    ranking = np.ones(len(a), dtype = int) # dtype is very important!
    # loop over the array
    for i in range(len(a)):
        # loop over all the remaining items ahead of the current item
        for j in range(i+1, len(a)):
            # check if the remaining items have lower rank but higher value
            # if this is the case, increase the rank of the further items and assign them as parent
            if a[i] < a[j] and ranking[i] >= ranking[j]:
                ranking[j] = ranking[i] + 1
    print(ranking)
    max_rank_at = int(max(ranking))
    order_list = []
    for each_rank in reversed(range(len(ranking))):
        if ranking[each_rank] == max_rank_at:
            order_list.insert(0, a[each_rank])
            max_rank_at -= 1
    return order_list      
    
longest_increasing_subsequence(test_array)

[1 1 2 3 3 4]


[0, 1, 2, 10]

In [11]:
# Longest Common Increasing Subsequence of two arrays

arr1 = [4, 0, 8, 2, 10] # LCS: 4,8,2,10 & LCIS: 4, 8, 10 & LCIS should be: [0,1,2,1,3]
arr2 = [3, 4, 8, 2, 10]

# find the longest common subsequence
def lcsubseq(X, Y):
    if len(X) == 0 or len(Y) == 0: return None
    n = len(X)
    m = len(Y)
    memo = np.zeros([n+1, m+1], dtype = int)
    for i in range(1,n+1):
        for j in range(1,m+1):
            if X[i-1] == Y[j-1]:
                memo[i][j] = memo[i-1][j-1] + 1
            else:
                memo[i][j] = max(memo[i][j-1], memo[i-1][j])
    # percolate up to find the items that have matched
    i = n
    j = m
    lcsubseq_list = []
    while i > 0 and j > 0:
        if X[i-1] == Y[j-1]:
            lcsubseq_list.insert(0, X[i-1])
            i -= 1
            j -= 1
        elif memo[i][j-1] > memo[i-1][j]:
            j -= 1
        else:
            i -= 1
    return lcsubseq_list

test_array = lcsubseq(arr1, arr2)
   
# Extract the longest increasing subsequence from the solution of the LCS of two arrays
def lisubs(array):
    n = len(array)
    ranking = np.ones(n, dtype = int)
    for i in range(n):
        for j in range(i, n):
            if array[j] > array[i] and ranking[i] >= ranking[j]:
                ranking[j] = ranking[i] + 1
    print(ranking)
    lis = []
    max_val = np.max(ranking)
    for i in reversed(range(n)):
        if ranking[i] == max_val:
            lis.insert(0, array[i])
            max_val -= 1
    return lis


lisubs(test_array)

[1 2 1 3]


[4, 8, 10]

In [12]:
# Find Maximum Sum Increasing Subsequence 
# Solution is also similar to Longest Increasing Subsequence with a twist
# Ex: If input is {1, 101, 2, 3, 100, 4, 5}, output is: 106 (1 + 2 + 3 + 100)


import numpy as np
def max_sum_increasing_subseq(arr): 
    n = len(arr)
    msis = np.copy(arr) # copy the values of original array as starting point
    # Compute maximum sum values in bottom up manner 
    for i in range(n): 
        for j in range(i): 
            if (arr[i] > arr[j] and msis[i] < msis[j] + arr[i]): 
                msis[i] = msis[j] + arr[i] 
    print(msis)
    # Pick maximum of all msis values 
    return np.max(msis)
  
test_array = [1, 101, 2, 3, 100, 4, 5]  
max_sum_increasing_subseq(test_array) 

[  1 102   3   6 106  10  15]


106

In [13]:
# Minimum number of jumps to reach the end of the array
# Given an array of integers where each element represents the max number of steps that can be made forward from that 
# element. Return the minimum number of jumps to reach the end of the array (starting from the first element). 
# If an element is 0, then cannot move through that element.

# Example: Input: arr[] = {1, 3, 5, 8, 9, 2, 6, 7, 6, 8, 9} then Output: 3 (1-> 3 -> 8 ->9)
# First element is 1, so can only go to 3. Second element is 3, so can make at most 3 steps eg to 5 or 8 or 9.

def min_jumps_to_reach_the_end_of_array(arr):
    n = len(arr)
    if n == 0 or arr[0] == 0: return  
    jumps = [np.inf] * n 
    jumps[0] = 0
    for i in range(1, n):  
        for j in range(i): 
            current_distance = i-j
            potential_steps = arr[j]
            if (current_distance <= potential_steps): # if potential steps are larger, it will be faster to reach to end
                jumps[i] = min(jumps[i], jumps[j] + 1) 
    print(jumps)
    return jumps[n-1] 
  
# Driver Program to test above function 
arr = [1, 3, 2, 5, 6, 4, 2, 6, 7, 6, 8, 9, 11] 
min_jumps_to_reach_the_end_of_array(arr)

[0, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4]


4

In [14]:
# Dynamic programming solution to find all possible steps to cover a distance problem 
# Reach a target by using a list of all integers that are all smaller than or equal to the target

steps = [1,2,3]
target = 5

def count_ways_to_reach_target(target, step_list): 
    res = [0 for x in range(target+1)] # Creates list res with all elements 0 
    res[0] = 1 
    for i in range(1, target+1): 
        for j in [c for c in step_list if c <= target]:
            res[i] += res[i-j]
    print(res)
    return res[target]
print(count_ways_to_reach_target(target,steps)) 
# %timeit count_ways_to_reach_target(target, steps)


[1, 1, 2, 4, 7, 13]
13


In [15]:
# number of ways to cover a distance if it was made with recursion

def reach_t(list_of_numbers, target, result = None, sub_solution = None):
    if result == None: result = []
    if sub_solution == None: sub_solution = []
    if sum(sub_solution) > target: return
    if sum(sub_solution) == target: result.append(sub_solution)
    # loop over all the items in the list
    for i in range(len(list_of_numbers)):
        reach_t(list_of_numbers, target, result, sub_solution + [list_of_numbers[i]])
    return result

solution = reach_t([1,2,3], 5)
print(solution, len(solution))
%timeit reach_t([1,2,3], 5)

# print the min number of steps (number of items to add up) to reach the target:
print(min([len(solution[i]) for i in range(len(solution))]))  # takes minimum 2 items to sum up to reach target


[[1, 1, 1, 1, 1], [1, 1, 1, 2], [1, 1, 2, 1], [1, 1, 3], [1, 2, 1, 1], [1, 2, 2], [1, 3, 1], [2, 1, 1, 1], [2, 1, 2], [2, 2, 1], [2, 3], [3, 1, 1], [3, 2]] 13
106 µs ± 53.3 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
2


In [16]:
# Count the number of ways to traverse a Matrix with Time Complexity : O(m * n)  
# start from: matrix[0][0], end at: mat[m-1][n-1] 

def number_of_paths(m, n): 
    dp = np.ones([m, n], dtype = int) 
    for i in range(1, m): 
        for j in range(1, n): 
            dp[i][j] = (dp[i - 1][j] + dp[i][j - 1])              
    print(dp)
    return dp[-1][-1]

n = 5
m = 5
print(number_of_paths(n, m))

[[ 1  1  1  1  1]
 [ 1  2  3  4  5]
 [ 1  3  6 10 15]
 [ 1  4 10 20 35]
 [ 1  5 15 35 70]]
70


In [17]:
# Optimal Strategy for a Game for 2 players picking coins from an array of coins, trying to get maximum value
# Consider a row of n coins, where n is even and two players alternating turns. In each turn, a player selects either 
# the first or last coin from the row, removes it from the row permanently. Find the max value a player can get.

# Returns optimal value possible that 
# a player can collect from an array  
# of coins of size n. 

def strategy_to_earn_most_money_in_a_game(arr, n): 
    table = np.zeros([n,n] ,dtype = int) 
    # the table is filled in diagonal fashion  
    for gap in range(n): 
        for j in range(gap, n): 
            i = j - gap 
            x = 0
            if((i + 2) <= j): 
                x = table[i + 2][j] 
            y = 0
            if((i + 1) <= (j - 1)): 
                y = table[i + 1][j - 1] 
            z = 0
            if(i <= (j - 2)): 
                z = table[i][j - 2] 
            table[i][j] = max(arr[i] + min(x, y), arr[j] + min(y, z)) 
            
    return table[0][n - 1] 
  
# Driver Code 
arr1 = [ 20, 9, 2, 2, 2, 10]  
n = len(arr1) 
print(strategy_to_earn_most_money_in_a_game(arr1, n)) 


# Alternatively it would be better to use this easy solution:
# player 1 is smart and making the best choices and player 2 is a total loser:

import copy
array = [ 20, 9, 2, 2, 2, 10]
player1 = []
player2 = []
cp_array = copy.deepcopy(array)
while len(cp_array) >= 2:
    max_item = max(cp_array[0], cp_array[-1])
    min_item = min(cp_array[0], cp_array[-1])
    player1.append(max_item)
    player2.append(min_item)
    cp_array.remove(max_item)
    cp_array.remove(min_item)
print(max(sum(player1), sum(player2)))
    


31
31


In [18]:
# find out if any combination of elements in an array sums up to target with time complexity O(n*target)
# the algoritm is similar to knapsack algorithm to build the dp

import numpy as np  
test_array = [5,4,1,2,7,8,3]

def sum_subset(array, target): 
    n = len(array)
    dp = np.zeros([n+1, target+1], dtype = int)
    for i in range(n+1):
        for t in range(target+1):
            dp[i][0] = 1 # it is crucial to start with True for reaching 0 with any item
            if array[i-1] <= t:
                curr_val = array[i-1]
                dp[i][t] = dp[i-1][t] or dp[i-1][t-curr_val]
            else:
                dp[i][t] = dp[i-1][t]
    if dp[n][target] == 1: 
        print('target is reachable')
    print(dp)
    set_of_items = []
    # Start from last element and percolate up
    i = n  
    currSum = target 
    while (i > 0 and currSum > 0): 
        if (dp[i - 1][currSum]): # if previous items already add up, then exclude current item and move to the next
            i -= 1
        elif (dp[i - 1][currSum - array[i - 1]]):# if the previous item is necessary to reach the target, include it
            set_of_items.append(array[i-1]) 
            currSum -= array[i-1] 
            i -= 1
    return set_of_items
sum_subset(test_array, 23)
# solution is [8, 7, 2, 1, 5]
    


target is reachable
[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 1 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


[8, 7, 2, 1, 5]

In [19]:
# Recursive solution of the above problem would be very costly but it will give all combinations to the solution:
# NOT recommended for large size problems!

def find_subset_to_reach_target(array, target, result = None, subset = None):
    if result == None: result = []
    if subset == None: subset = []
    if sum(subset) == target: result.append(subset)
    if sum(subset) > target: return
    for i in range(len(array)):
        remaining = array[:i+1]
        if array[i] not in subset: # make sure each element is included only once
            find_subset_to_reach_target(remaining, target, result, subset + [array[i]])
    return result
    # return [n for i,n in enumerate(result) if n not in result[:i]] # avoid repetitions if any in the original array

find_subset_to_reach_target([5,4,1,2,7,8,3], 23)

[[8, 7, 2, 1, 5], [3, 8, 2, 1, 4, 5], [3, 8, 7, 5], [3, 8, 7, 1, 4]]

In [20]:
# Dynamic programming solution for equal sum sub-sets partition problem with time complexity: O(n*k)
# Same algorithm with finding if any combination of sum of some elements in a list is equal to the target. 

arr1 = [5,4,1,2,5,2,3]
import numpy as np  

def print_two_equal_sum_subsets(arr): 
    n = len(arr)
    if sum(arr) % 2 == 1: return False # if sum / 2 is odd the array can't be partitioned to two equal subsets 
    k = sum(arr) // 2  # the sum of both subsets will be k 
    # dp[i][j] = 1 if there is a subset of elements in first i elements of array that has sum equal to j.  
    memo_table = np.zeros((n + 1, k + 1))   
    for i in range(n + 1):  # TRUE if the array has 0 elements
        memo_table[i][0] = 1
    # check if the any combination of elements until index i, is equal to curr_sum 
    for i in range(1, n + 1): # traverse each element
        for currSum in range(1, k + 1):  # for each sum subset value
            if arr[i-1] <= currSum: # if current item can fit to the sum
                memo_table[i][currSum] = memo_table[i-1][currSum] or memo_table[i-1][currSum - arr[i-1]]
            else:
                memo_table[i][currSum] = memo_table[i-1][currSum]
    
    # If the answer needed was a TRUE or FALSE, we could just return the dp[n][k] value
    print(memo_table) # view the memo table 
    
    # If partition is not possible, return False 
    if memo_table[n][k] == 0: return False
    
    # partition part requires creating two sets and separating the items list 
    set1, set2 = [], [] 

    # Start from last element and percolate up
    i = n  
    currSum = k  
    while (i > 0 and currSum >= 0): 
        if (memo_table[i - 1][currSum]): 
            set1.append(arr[i-1]) 
            print('item: {} goes to set 1, see indices {} and {} is 1'.format(arr[i-1], i-1, currSum))  
        elif (memo_table[i - 1][currSum - arr[i - 1]]): 
            print('item: {} goes to set 2, see indices {} and {} is 0'.format(arr[i-1], i-1, currSum))
            set2.append(arr[i-1]) 
            currSum -= arr[i-1] 
        i -= 1

    return set1, set2 
  
# arr1 = [5,4,1,2]
print_two_equal_sum_subsets(arr1)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0.]
 [1. 1. 0. 0. 1. 1. 1. 0. 0. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
item: 3 goes to set 1, see indices 6 and 11 is 1
item: 2 goes to set 1, see indices 5 and 11 is 1
item: 5 goes to set 1, see indices 4 and 11 is 1
item: 2 goes to set 2, see indices 3 and 11 is 0
item: 1 goes to set 1, see indices 2 and 9 is 1
item: 4 goes to set 2, see indices 1 and 9 is 0
item: 5 goes to set 2, see indices 0 and 5 is 0


([3, 2, 5, 1], [2, 4, 5])

In [21]:
# Rod cutting profit optimization
# Very similiar to finding minimum number of coins to reach a target change algorithm

import numpy as np
price_list = [1, 5, 8, 9, 10, 17, 17, 20]
def rod_cutting_max_profit(array):
    n = len(array)
    dp = np.copy(array)
    dp = np.insert(dp, 0, 0)
    for i in range(len(dp)):
        for j in range(i):
            dp[i] = max(dp[i], dp[i-j] + dp[j])
    print(dp) # to view the dp        
    return dp[n]       
rod_cutting_max_profit(price_list) 

# Alternative Solution:
# def rod_cutting_price_optimization(pricing_list):
#     n = len(pricing_list)
#     known_results = np.copy(pricing_list) # np.copy is a deep copy by default
#     for i in range(n):
#         for j in range(i): # since each cut is only 1 inches, check the length 
#             known_results[i] = max(known_results[i-j-1] + known_results[j], known_results[i])
#     print(known_results) # view the array build up     
#     return known_results[n-1] # view the whole list for all optinal solutions

# rod_cutting_price_optimization(price_list)

[ 0  1  5  8 10 13 17 18 22]


22

In [22]:
# Word Break Problem with Hashing:

test1 = "bunniesareawesome"
test2 = "bunniesadfadfareawesome"
list_of_substr = ["bunn", "a" , "awesome", "ies", "re"]

# create a function that takes the string and the substring list, outputs if substrings are all found in the string
def word_break(string, words):
    n = len(string)
    # create a memo table
    memo = {}
    for i in range(n): # traverse the string,
        for j in range(i): # traverse each letter until i
            if string[j:i+1] in words: # include all indices 
                memo[string[j:i+1]] = 'True'           
    print(memo.keys(), words)
    for i in words:
        if i not in memo.keys():
            return False
    
    return True 

print(word_break(test1, list_of_substr))
print(word_break(test2, list_of_substr))



# Alternative Solution:
# string = "bunniesadfadfareawesome"
# words = ["bunn", "a" , "awesome", "ies", "re"]

# # create a function that takes the string and the substring list, outputs if substrings are all found in the string
# def words_in_a_string(string, word_list):
#     # create a set
#     checked_words = set()
#     word_list = set(word_list)
#     n = len(string)
#     for i in range(1, n+1): # traverse the string, index i is starting from 1
#         for j in range(i): # traverse each letter until i
#             if string[j:i] in word_list and string[j:i] not in checked_words:
#                 checked_words.add(string[j:i])
#     return checked_words == word_list   
    
# print(words_in_a_string(string, words))

dict_keys(['bunn', 'ies', 're', 'awesome']) ['bunn', 'a', 'awesome', 'ies', 're']
False
dict_keys(['bunn', 'ies', 're', 'awesome']) ['bunn', 'a', 'awesome', 'ies', 're']
False
